apiVersion: apps/v1
kind: Deployment
metadata:
  name: cake-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cake-manager
  template:
    metadata:
      labels:
        app: cake-manager
    spec:
      containers:
        - name: cake-manager
          image: gcr.io/cake-manager-project/cake-manager:latest
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8282
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8282
            initialDelaySeconds: 40
            periodSeconds: 10
          imagePullPolicy: Always
          ports:
            - containerPort: 8282
          env:
            - name: PORT
              value: "8282"